"""Generate a C header + source file embedding a TFLite model as a byte array.

This is the Linux/Python equivalent of Nuvoton's Windows-only
``gen_model_cpp.exe`` that ships with the ML_YOLO sample. The output format
matches what the M55M1 TFLM samples expect:

* ``<name>.h`` declares ``extern const unsigned char <name>[];`` and
  ``extern const unsigned int <name>_len;`` plus a few model-info externs.
* ``<name>.cc`` defines those symbols and embeds the model bytes in a
  ``__attribute__((aligned(16)))`` array placed in a section named
  ``.rodata.tflm_model`` so the linker can put it in flash.

The model byte array name defaults to the input filename (with non-identifier
characters replaced by ``_``). If the input path is the Vela-compiled file the
output usually ends up named e.g. ``model_int8_vela`` -- match what the
firmware ``main.c`` references.

Usage:
    python scripts/gen_model_header.py <input.tflite> [-o <out_dir>] \
        [--name <symbol>] [--image-size 192] [--channels 3] [--num-classes 1]
"""

from __future__ import annotations

import argparse
import re
from pathlib import Path


HEADER_TEMPLATE = """\
// Auto-generated by scripts/gen_model_header.py. Do not edit by hand.
#ifndef {guard}
#define {guard}

#ifdef __cplusplus
extern "C" {{
#endif

extern const unsigned char {name}[];
extern const unsigned int  {name}_len;

// Model metadata (fed into post-processing). These mirror the Nuvoton
// ML_YOLO ``variables.bat`` exports.
extern const int originalImageSize;
extern const int channelsImageDisplayed;
extern const int numClasses;
extern const int gridSize;

#ifdef __cplusplus
}}
#endif

#endif  // {guard}
"""


SOURCE_TEMPLATE = """\
// Auto-generated by scripts/gen_model_header.py. Do not edit by hand.
#include "{header}"

#if defined(__GNUC__) || defined(__clang__)
#define MODEL_ALIGN __attribute__((aligned(16)))
#define MODEL_SECTION __attribute__((section(".rodata.tflm_model")))
#else
#define MODEL_ALIGN
#define MODEL_SECTION
#endif

const unsigned char {name}[] MODEL_ALIGN MODEL_SECTION = {{
{bytes}
}};
const unsigned int {name}_len = {length}u;

const int originalImageSize       = {image_size};
const int channelsImageDisplayed  = {channels};
const int numClasses              = {num_classes};
const int gridSize                = {grid_size};
"""


def _sanitize_symbol(name: str) -> str:
    s = re.sub(r"[^0-9a-zA-Z_]", "_", name)
    if s and s[0].isdigit():
        s = "_" + s
    return s or "model"


def _format_bytes(data: bytes, per_line: int = 16) -> str:
    lines = []
    for i in range(0, len(data), per_line):
        chunk = data[i:i + per_line]
        lines.append("    " + ", ".join(f"0x{b:02x}" for b in chunk) + ",")
    if lines:
        # Trailing comma is fine in C, leave as-is for clarity.
        pass
    return "\n".join(lines)


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("input", type=Path, help="Path to the .tflite file (vela-compiled).")
    parser.add_argument("-o", "--output-dir", type=Path, default=None,
                        help="Directory to write .h/.cc files into. Default: alongside the input.")
    parser.add_argument("--name", default=None,
                        help="Symbol name. Default: input filename without extension.")
    parser.add_argument("--image-size", type=int, default=192)
    parser.add_argument("--channels", type=int, default=3)
    parser.add_argument("--num-classes", type=int, default=1)
    parser.add_argument("--grid-size", type=int, default=6)
    args = parser.parse_args()

    if not args.input.exists():
        raise SystemExit(f"input not found: {args.input}")

    output_dir = args.output_dir or args.input.parent
    output_dir.mkdir(parents=True, exist_ok=True)

    raw_name = args.name or args.input.stem
    name = _sanitize_symbol(raw_name)

    data = args.input.read_bytes()
    header_path = output_dir / f"{raw_name}.h"
    source_path = output_dir / f"{raw_name}.cc"

    guard = name.upper() + "_H_"

    header_path.write_text(HEADER_TEMPLATE.format(guard=guard, name=name))
    source_path.write_text(SOURCE_TEMPLATE.format(
        header=header_path.name,
        name=name,
        bytes=_format_bytes(data),
        length=len(data),
        image_size=args.image_size,
        channels=args.channels,
        num_classes=args.num_classes,
        grid_size=args.grid_size,
    ))

    print(f"[gen_model_header] wrote {header_path} ({len(data)} bytes embedded)")
    print(f"[gen_model_header] wrote {source_path}")


if __name__ == "__main__":
    main()
